### PR TITLE
Improvement registration

### PR DESCRIPTION
**Pull request by JDonut**
Change redirect location on account creation to make a little more sense

### CODE REVIEW

**Comment by mdw7326** [comment]
What needs love? It's the same old bootstrap form right?

**Comment by JDonut** [comment]
I might have butchered the style on it when I moved it over to the main project. And by "might have", I mean definitely. Sorry :(

**Comment by mdw7326** [comment]
It looks perfectly fine when I run it

**Comment by mdw7326** [comment]
ah you were talking about the user info form. See #16

**Pull request merged**
